# Querying [tmdb](https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata) movie information from aperturedb.

This notebook will work on an instance of ApertureDB, which can be on the [cloud](https://cloud.aperturedata.io), or running as a [local docker container(s)](https://docs.aperturedata.io/Setup/server/Local)

The dataset is hosted on kaggle, and available via a mlcroissant link.

In [4]:
%pip install --quiet mlcroissant pandas dotenv

Note: you may need to restart the kernel to use updated packages.

## Import all the modules needed

In [5]:
import pandas as pd
from IPython.display import display


from aperturedb.CommonLibrary import (
    execute_query,
    create_connector
)
from aperturedb.Utils import Utils

In [6]:
client=create_connector()
utils = Utils(client)
utils.summary()

================== Summary ==================
Database: localhost
Version: 0.18.10
Status:  0
Info:    OK
------------------ Entities -----------------
Total entities types:    6
GENRE
  Total elements: 20
I   Number   | id     |        20 (100%)
    String   | label  |        20 (100%)
    String   | name   |        20 (100%)
KEYWORD
  Total elements: 9813
I   Number   | id     |      9813 (100%)
    String   | label  |      9813 (100%)
    String   | name   |      9813 (100%)
MOVIE
  Total elements: 4803
    Number   | budget        |      4803 (100%)
I   String   | id            |      4803 (100%)
    String   | label         |      4803 (100%)
  ! Number   | movie_id      |      4803 (100%)
    String   | name          |      4803 (100%)
    String   | overview      |      4803 (100%)
    Number   | popularity    |      4803 (100%)
    String   | tagline       |      4803 (100%)
    String   | title         |      4803 (100%)
    Number   | vote_average  |      4803 (100%)
    Number   | vote_count    |      4803 (100%)
PRODUCTION_COMPANY
  Total elements: 5047
I   Number   | id     |      5047 (100%)
    String   | label  |      5047 (100%)
    String   | name   |      5047 (100%)
PROFESSIONAL
  Total elements: 104842
    Number   | gender  |    104842 (100%)
I   Number   | id      |    104842 (100%)
    String   | label   |    104842 (100%)
    String   | name    |    104842 (100%)
SPOKEN_LANGUAGE
  Total elements: 87
I   String   | iso_639_1  |        87 (100%)
    String   | label      |        87 (100%)
    String   | name       |        87 (100%)
---------------- Connections ----------------
Total connections types: 6
CAST
  MOVIE ====> PROFESSIONAL
  Total elements: 106257
I   Number   | cast_id    |    106257 (100%)
    String   | character  |    106257 (100%)
    String   | name       |    106257 (100%)
CREW
  MOVIE ====> PROFESSIONAL
  Total elements: 129581
  ! String   | credit_id   |    129581 (100%)
    String   | department  |    129581 (100%)
    String   | job         |    129581 (100%)
    String   | name        |    129581 (100%)
HAS_GENRE
  MOVIE ====> GENRE
  Total elements: 12160
    String   | name  |     12160 (100%)
HAS_KEYWORD
  MOVIE ====> KEYWORD
  Total elements: 36194
    String   | name  |     36194 (100%)
HAS_PRODUCTION_COMPANY
  MOVIE ====> PRODUCTION_COMPANY
  Total elements: 13677
    String   | name  |     13677 (100%)
HAS_SPOKEN_LANGUAGE
  MOVIE ====> SPOKEN_LANGUAGE
  Total elements: 6937
    String   | name  |      6937 (100%)
------------------ Totals -------------------
Total nodes: 124612
Total edges: 304806
=============================================

## Query time!
### Find all the movies where Tom Hanks as been a part of

In [7]:
q = [
    {
        "FindEntity": {
            "_ref": 1,
            "with_class": "PROFESSIONAL",
            "constraints": {
                "name": ["==", "Tom hanks"]
            },
            "results": {
                "all_properties": True
            }
        }
    },
    {
        "FindEntity": {
            "_ref": 2,
            "is_connected_to": {
                "ref": 1
            },
            "with_class": "MOVIE",
            "results": {
                # "list": ["id", "title"]
                "all_properties": True
            }
        }
    }
]

_, response, _ = execute_query(client, q)

display(pd.json_normalize(response[0]["FindEntity"]["entities"]))
display(pd.json_normalize(response[1]["FindEntity"]["entities"]))

movie_ids = [e["movie_id"] for e in response[1]["FindEntity"]["entities"]]
display(movie_ids)

        _uniqueid  gender  id         label       name
0  33.1648.483960       2  31  PROFESSIONAL  Tom hanks

,_uniqueid,budget,id,label,movie_id,name,overview,popularity,tagline,title,vote_average,vote_count
0,32.29.483960,40000000,64685,MOVIE,64685,Extremely loud & incredibly close,"A year after his father's death, Oskar, a trou...",31.066874,"This is not a story about September 11th, it's...",Extremely Loud & Incredibly Close,6.9,708
1,32.379.483966,26000000,9800,MOVIE,9800,Philadelphia,No one would take his case until one man was w...,44.301745,No one would take on his case... until one man...,Philadelphia,7.6,988
2,32.642.483972,200000000,10193,MOVIE,10193,Toy story 3,"Woody, Buzz, and the rest of Andy's toys haven...",59.995418,No toy gets left behind.,Toy Story 3,7.6,4597
3,32.673.483972,175000000,2698,MOVIE,2698,Evan almighty,God contacts Congressman Evan Baxter and tells...,27.082182,A comedy of biblical proportions,Evan Almighty,5.3,1151
4,32.690.483972,165000000,5255,MOVIE,5255,The polar express,When a doubting young boy takes an extraordina...,47.323228,This holiday season... believe.,The Polar Express,6.4,1474
5,32.727.483974,70000000,857,MOVIE,857,Saving private ryan,"As U.S. troops storm the beaches of Normandy, ...",76.041867,The mission is a man.,Saving Private Ryan,7.9,5048
6,32.734.483974,52000000,568,MOVIE,568,Apollo 13,The true story of technical troubles that scut...,68.140214,"Houston, we have a problem.",Apollo 13,7.3,1599
7,32.737.483974,65000000,9489,MOVIE,9489,You've got mail,"Book superstore magnate, Joe Fox and independe...",28.540267,Someone you pass on the street may already be ...,You've Got Mail,6.3,838
8,32.789.483974,60000000,497,MOVIE,497,The green mile,A supernatural tale set on death row in a Sout...,103.698022,Miracles do happen.,The Green Mile,8.2,4048
9,32.820.483976,55000000,13600,MOVIE,13600,City of ember,"For generations, the people of the City of Emb...",23.465539,Escape is the only option,City of Ember,6.2,605
10,32.884.483976,35000000,140823,MOVIE,140823,Saving mr. banks,Author P.L. Travers travels from London to Hol...,31.957947,"Where her book ended, their story began.",Saving Mr. Banks,7.3,1226
11,32.895.483976,0,5516,MOVIE,5516,The ladykillers,"An eccentric, if not charming Southern profess...",23.666229,The greatest criminal minds of all time have f...,The Ladykillers,6.0,415
12,32.1059.483980,1000000,13508,MOVIE,13508,Who killed the electric car?,"In 1996, electric cars began to appear on road...",5.323184,A lack of consumer confidence... or conspiracy?,Who Killed the Electric Car?,7.2,59
13,32.1428.483988,150000000,13448,MOVIE,13448,Angels & demons,Harvard symbologist Robert Langdon investigate...,67.447636,None,Angels & Demons,6.5,2129
14,32.1653.483992,35000000,20763,MOVIE,20763,Radio flyer,A father reminisces about his childhood when h...,3.503408,Powered by imagination.,Radio Flyer,6.6,53
15,32.2032.484000,8000000,2619,MOVIE,2619,Splash,A successful businessman falls in love with th...,21.735068,Allen Bauer Thought He'd Never Find The Right ...,Splash,6.1,321
16,32.2201.484004,125000000,591,MOVIE,591,The da vinci code,When the curator of the Louvre is found murder...,45.313197,Seek the truth.,The Da Vinci Code,6.5,2704
17,32.2293.484004,100000000,16523,MOVIE,16523,Where the wild things are,Max imagines running away from his mom and sai...,31.586215,There's one in all of us.,Where the Wild Things Are,6.4,572
18,32.2308.484006,55000000,13,MOVIE,13,Forrest gump,A man with a low IQ has accomplished great thi...,138.133331,"The world will never be the same, once you've ...",Forrest Gump,8.2,7927
19,32.2317.484006,55000000,109424,MOVIE,109424,Captain phillips,The true story of Captain Richard Phillips and...,52.786917,Out here survival is everything.,Captain Phillips,7.6,2454
20,32.2382.484006,52000000,640,MOVIE,640,Catch me if you can,"A true story about Frank Abagnale Jr. who, bef...",73.944049,The true story of a real fake.,Catch Me If You Can,7.7,3795
21,32.2385.484006,52000000,11631,MOVIE,11631,Mamma mia!,"Set on an idyllic Greek island, the plot serve...",30.780599,Take a trip down the aisle you'll never forget,Mamma Mia!,6.4,1386
22,32.2439.484008,30000000,862,MOVIE,862,Toy story,"Led by Woody, Andy's toys live happily in his ...",73.640445,None,Toy Story,7.7,5269
23,32.3001.484020,102000000,83542,MOVIE,83542,Cloud atlas,A set of six nested stories spanning time betw...,73.872343,Everything is Connected,Cloud Atlas,6.6,2977
24,32.3043.484020,90000000,863,MOVIE,863,Toy story 2,"Andy heads off to Cowboy Camp, leaving his toy...",73.575118,The toys are back!,Toy Story 2,7.3,3806
25,32.3084.484020,90000000,8358,MOVIE,8358,Cast away,"Chuck, a top international manager for FedEx, ...",57.739713,"At the edge of the world, his journey begins.",Cast Away,7.5,3218
26,32.3210.484024,30000000,59861,MOVIE,59861,Larry crowne,"After losing his job, a middle-aged man reinve...",20.355458,Rediscover life and love,Larry Crowne,5.7,359
27,32.3304.484026,0,9591,MOVIE,9591,That thing you do!,A Pennsylvania band scores a hit in 1964 and r...,14.885388,In every life there comes a time when that dre...,That Thing You Do!,6.8,225
28,32.3844.484036,80000000,4147,MOVIE,4147,Road to perdition,Mike Sullivan works as a hit man for crime bos...,49.078546,Pray for Michael Sullivan.,Road to Perdition,7.3,1077
29,32.3977.484038,50000000,9906,MOVIE,9906,The ant bully,Fed up with being targeted by the neighborhood...,20.239061,The battle for the lawn is on.,The Ant Bully,5.5,366
30,32.4484.484048,5000000,8346,MOVIE,8346,My big fat greek wedding,A young Greek woman falls in love with a non-G...,18.115566,Love is here to stay... so is her family.,My Big Fat Greek Wedding,6.2,671
31,32.4507.484050,18000000,2280,MOVIE,2280,Big,"A young boy, Josh Baskin makes a wish at a car...",20.716023,You're Only Young Once But For Josh It Might J...,Big,6.9,993
32,32.4518.484050,18000000,302688,MOVIE,302688,My big fat greek wedding 2,The continuing adventures of the Portokalos fa...,16.027955,People change. Greeks don't.,My Big Fat Greek Wedding 2,5.5,322
33,32.4617.484052,60000000,594,MOVIE,594,The terminal,Viktor Navorski is a man without a country; hi...,57.753914,Life is waiting.,The Terminal,7.0,1910
34,32.4620.484052,75000000,6538,MOVIE,6538,Charlie wilson's war,The true story of Texas congressman Charlie Wi...,18.700310,Based on a true story. You think we could make...,Charlie Wilson's War,6.5,338
35,32.4654.484052,75000000,35,MOVIE,35,The simpsons movie,After Homer accidentally pollutes the town's w...,46.875375,See our family. And feel better about yours.,The Simpsons Movie,6.9,2264
36,32.4662.484052,120000000,920,MOVIE,920,Cars,"Lightning McQueen, a hotshot rookie race car d...",82.643036,Ahhh... it's got that new movie smell.,Cars,6.6,3877
37,32.4754.484054,40000000,11287,MOVIE,11287,A league of their own,Small-town sisters Dottie and Kit join an all-...,21.661028,"To achieve the incredible, you have to attempt...",A League of Their Own,6.7,354
38,32.4782.484054,40000000,296098,MOVIE,296098,Bridge of spies,"During the Cold War, the Soviet Union captures...",48.445978,"In the shadow of war, one man showed the world...",Bridge of Spies,7.2,2583

[64685,
 9800,
 10193,
 2698,
 5255,
 857,
 568,
 9489,
 497,
 13600,
 140823,
 5516,
 13508,
 13448,
 20763,
 2619,
 591,
 16523,
 13,
 109424,
 640,
 11631,
 862,
 83542,
 863,
 8358,
 59861,
 9591,
 4147,
 9906,
 8346,
 2280,
 302688,
 594,
 6538,
 35,
 920,
 11287,
 296098]

### Get more info.

This response from cast and movies entities still misses the character information, because it's been encoded on the properties on connection between the 2. Let's merge that info in and get more richer details about the movies Tom Hanks has been a part of.

In [8]:
professional = pd.json_normalize(response[1]["FindEntity"]["entities"])

professional_details = []
for p in response[0]["FindEntity"]["entities"]:
    src = p["_uniqueid"]
    for m in response[1]["FindEntity"]["entities"]:
        dst = m["_uniqueid"]
        q = [{
            "FindEntity": {
                "_ref": 1,
                "with_class": "PROFESSIONAL",
                "constraints": {
                    "_uniqueid": ["==", src]
                },
                "results": {
                    "all_properties": True
                }
            }
        },
        {
            "FindEntity": {
                "_ref": 2,
                "is_connected_to": {
                    "ref": 1
                },
                "with_class": "MOVIE",
                "constraints": {
                    "_uniqueid": ["==", dst]
                },
                "results": {
                    "all_properties": True
                }
            }
        },{
            "FindConnection": {
                "src": 2,
                "dst": 1,
                "results": {
                    "all_properties": True
                }
            }
        }]
        _, responsec, _ = execute_query(client, q)
        # print(f"{response=}")

        if responsec[2]["FindConnection"]["returned"] > 0:
            c = responsec[2]["FindConnection"]["connections"][0]
            # print(f"{p['name']} has acted in {m['title']} as {c['character']}")
            # print(f"{p['name']} has contributed in {m['title']}")
            if "character" in c:
                professional_details.append(f"as character: {c['character']}")
            else:
                professional_details.append(f"as {c['job']} in {c['department']}")
            # display(pd.json_normalize(response[3]["FindConnection"]["connections"]))
display(len(professional_details))
professional['details'] = professional_details

display(professional)

39

,_uniqueid,budget,id,label,movie_id,name,overview,popularity,tagline,title,vote_average,vote_count,details
0,32.29.483960,40000000,64685,MOVIE,64685,Extremely loud & incredibly close,"A year after his father's death, Oskar, a trou...",31.066874,"This is not a story about September 11th, it's...",Extremely Loud & Incredibly Close,6.9,708,as character: Thomas Schell
1,32.379.483966,26000000,9800,MOVIE,9800,Philadelphia,No one would take his case until one man was w...,44.301745,No one would take on his case... until one man...,Philadelphia,7.6,988,as character: Andrew Beckett
2,32.642.483972,200000000,10193,MOVIE,10193,Toy story 3,"Woody, Buzz, and the rest of Andy's toys haven...",59.995418,No toy gets left behind.,Toy Story 3,7.6,4597,as character: Woody (voice)
3,32.673.483972,175000000,2698,MOVIE,2698,Evan almighty,God contacts Congressman Evan Baxter and tells...,27.082182,A comedy of biblical proportions,Evan Almighty,5.3,1151,as Executive Producer in Production
4,32.690.483972,165000000,5255,MOVIE,5255,The polar express,When a doubting young boy takes an extraordina...,47.323228,This holiday season... believe.,The Polar Express,6.4,1474,as character: Hero Boy / Father / Conductor / ...
5,32.727.483974,70000000,857,MOVIE,857,Saving private ryan,"As U.S. troops storm the beaches of Normandy, ...",76.041867,The mission is a man.,Saving Private Ryan,7.9,5048,as character: Captain John H. Miller
6,32.734.483974,52000000,568,MOVIE,568,Apollo 13,The true story of technical troubles that scut...,68.140214,"Houston, we have a problem.",Apollo 13,7.3,1599,as character: Jim Lovell
7,32.737.483974,65000000,9489,MOVIE,9489,You've got mail,"Book superstore magnate, Joe Fox and independe...",28.540267,Someone you pass on the street may already be ...,You've Got Mail,6.3,838,as character: Joe Fox
8,32.789.483974,60000000,497,MOVIE,497,The green mile,A supernatural tale set on death row in a Sout...,103.698022,Miracles do happen.,The Green Mile,8.2,4048,as character: Paul Edgecomb
9,32.820.483976,55000000,13600,MOVIE,13600,City of ember,"For generations, the people of the City of Emb...",23.465539,Escape is the only option,City of Ember,6.2,605,as Producer in Production
10,32.884.483976,35000000,140823,MOVIE,140823,Saving mr. banks,Author P.L. Travers travels from London to Hol...,31.957947,"Where her book ended, their story began.",Saving Mr. Banks,7.3,1226,as character: Walt Disney
11,32.895.483976,0,5516,MOVIE,5516,The ladykillers,"An eccentric, if not charming Southern profess...",23.666229,The greatest criminal minds of all time have f...,The Ladykillers,6.0,415,as character: Professor G.H. Dorr
12,32.1059.483980,1000000,13508,MOVIE,13508,Who killed the electric car?,"In 1996, electric cars began to appear on road...",5.323184,A lack of consumer confidence... or conspiracy?,Who Killed the Electric Car?,7.2,59,as character: Himself
13,32.1428.483988,150000000,13448,MOVIE,13448,Angels & demons,Harvard symbologist Robert Langdon investigate...,67.447636,None,Angels & Demons,6.5,2129,as character: Robert Langdon
14,32.1653.483992,35000000,20763,MOVIE,20763,Radio flyer,A father reminisces about his childhood when h...,3.503408,Powered by imagination.,Radio Flyer,6.6,53,as character: Older Mike/Narrator (uncredited)
15,32.2032.484000,8000000,2619,MOVIE,2619,Splash,A successful businessman falls in love with th...,21.735068,Allen Bauer Thought He'd Never Find The Right ...,Splash,6.1,321,as character: Allen Bauer
16,32.2201.484004,125000000,591,MOVIE,591,The da vinci code,When the curator of the Louvre is found murder...,45.313197,Seek the truth.,The Da Vinci Code,6.5,2704,as character: Robert Langdon
17,32.2293.484004,100000000,16523,MOVIE,16523,Where the wild things are,Max imagines running away from his mom and sai...,31.586215,There's one in all of us.,Where the Wild Things Are,6.4,572,as Producer in Production
18,32.2308.484006,55000000,13,MOVIE,13,Forrest gump,A man with a low IQ has accomplished great thi...,138.133331,"The world will never be the same, once you've ...",Forrest Gump,8.2,7927,as character: Forrest Gump
19,32.2317.484006,55000000,109424,MOVIE,109424,Captain phillips,The true story of Captain Richard Phillips and...,52.786917,Out here survival is everything.,Captain Phillips,7.6,2454,as character: Captain Richard Phillips
20,32.2382.484006,52000000,640,MOVIE,640,Catch me if you can,"A true story about Frank Abagnale Jr. who, bef...",73.944049,The true story of a real fake.,Catch Me If You Can,7.7,3795,as character: Carl Hanratty
21,32.2385.484006,52000000,11631,MOVIE,11631,Mamma mia!,"Set on an idyllic Greek island, the plot serve...",30.780599,Take a trip down the aisle you'll never forget,Mamma Mia!,6.4,1386,as Executive Producer in Production
22,32.2439.484008,30000000,862,MOVIE,862,Toy story,"Led by Woody, Andy's toys live happily in his ...",73.640445,None,Toy Story,7.7,5269,as character: Woody (voice)
23,32.3001.484020,102000000,83542,MOVIE,83542,Cloud atlas,A set of six nested stories spanning time betw...,73.872343,Everything is Connected,Cloud Atlas,6.6,2977,as character: Dr. Henry Goose / Hotel Manager ...
24,32.3043.484020,90000000,863,MOVIE,863,Toy story 2,"Andy heads off to Cowboy Camp, leaving his toy...",73.575118,The toys are back!,Toy Story 2,7.3,3806,as character: Woody (voice)
25,32.3084.484020,90000000,8358,MOVIE,8358,Cast away,"Chuck, a top international manager for FedEx, ...",57.739713,"At the edge of the world, his journey begins.",Cast Away,7.5,3218,as character: Chuck Noland
26,32.3210.484024,30000000,59861,MOVIE,59861,Larry crowne,"After losing his job, a middle-aged man reinve...",20.355458,Rediscover life and love,Larry Crowne,5.7,359,as character: Larry Crowne
27,32.3304.484026,0,9591,MOVIE,9591,That thing you do!,A Pennsylvania band scores a hit in 1964 and r...,14.885388,In every life there comes a time when that dre...,That Thing You Do!,6.8,225,as character: Mr. White
28,32.3844.484036,80000000,4147,MOVIE,4147,Road to perdition,Mike Sullivan works as a hit man for crime bos...,49.078546,Pray for Michael Sullivan.,Road to Perdition,7.3,1077,as character: Michael Sullivan
29,32.3977.484038,50000000,9906,MOVIE,9906,The ant bully,Fed up with being targeted by the neighborhood...,20.239061,The battle for the lawn is on.,The Ant Bully,5.5,366,as Producer in Production
30,32.4484.484048,5000000,8346,MOVIE,8346,My big fat greek wedding,A young Greek woman falls in love with a non-G...,18.115566,Love is here to stay... so is her family.,My Big Fat Greek Wedding,6.2,671,as Producer in Production
31,32.4507.484050,18000000,2280,MOVIE,2280,Big,"A young boy, Josh Baskin makes a wish at a car...",20.716023,You're Only Young Once But For Josh It Might J...,Big,6.9,993,"as character: Joshua ""Josh"" Baskin"
32,32.4518.484050,18000000,302688,MOVIE,302688,My big fat greek wedding 2,The continuing adventures of the Portokalos fa...,16.027955,People change. Greeks don't.,My Big Fat Greek Wedding 2,5.5,322,as Producer in Production
33,32.4617.484052,60000000,594,MOVIE,594,The terminal,Viktor Navorski is a man without a country; hi...,57.753914,Life is waiting.,The Terminal,7.0,1910,as character: Viktor Navorski
34,32.4620.484052,75000000,6538,MOVIE,6538,Charlie wilson's war,The true story of Texas congressman Charlie Wi...,18.700310,Based on a true story. You think we could make...,Charlie Wilson's War,6.5,338,as character: Charlie Wilson
35,32.4654.484052,75000000,35,MOVIE,35,The simpsons movie,After Homer accidentally pollutes the town's w...,46.875375,See our family. And feel better about yours.,The Simpsons Movie,6.9,2264,as character: Himself (voice)
36,32.4662.484052,120000000,920,MOVIE,920,Cars,"Lightning McQueen, a hotshot rookie race car d...",82.643036,Ahhh... it's got that new movie smell.,Cars,6.6,3877,as character: Woody Car (voice)
37,32.4754.484054,40000000,11287,MOVIE,11287,A league of their own,Small-town sisters Dottie and Kit join an all-...,21.661028,"To achieve the incredible, you have to attempt...",A League of Their Own,6.7,354,as character: Jimmy Dugan
38,32.4782.484054,40000000,296098,MOVIE,296098,Bridge of spies,"During the Cold War, the Soviet Union captures...",48.445978,"In the shadow of war, one man showed the world...",Bridge of Spies,7.2,2583,as character: James B. Donovan

### Find 2 cast poeple. Find the movies in which they both appear (Logical AND)

Here we search for Tom Hanks and Meg Ryan. The All in the Find Connected entity means that find a set which is connected to both the cast people.

In [9]:
from aperturedb.CommonLibrary import execute_query

q = [
    {
        "FindEntity": {
            "_ref": 1,
            "with_class": "PROFESSIONAL",
            "constraints":{
                "name": ["in", ["Tom hanks"]]
            },
            "results": {
                "all_properties": True
                # "list": ["name", "_uniqueid"]
            }
        }
    },
    {
        "FindEntity": {
            "_ref": 2,
            "with_class": "PROFESSIONAL",
            "constraints":{
                "name": ["in", [ "Meg ryan"]]
            },
            "results": {
                "all_properties": True
                # "list": ["name", "_uniqueid"]
            }
        }
    },
    {
        "FindEntity": {
            "is_connected_to": {
                "all": [
                {"ref": 1},
                {"ref": 2}
                ]
            },
            "with_class": "MOVIE",
            "results": {
                # "list": ["id", "title"],
                # "group_by_source": True
                "all_properties": True
            }
        }
    }
]

_, response, _ = execute_query(client, q)

pd.json_normalize(response[2]["FindEntity"]["entities"])

,_uniqueid,budget,id,label,movie_id,name,overview,popularity,tagline,title,vote_average,vote_count
0,32.737.483974,65000000,9489,MOVIE,9489,You've got mail,"Book superstore magnate, Joe Fox and independe...",28.540267,Someone you pass on the street may already be ...,You've Got Mail,6.3,838

## We can write the same queries in SPARQL.

In [10]:
from aperturedb.SPARQL import SPARQL
import json


sparql = SPARQL(client, debug=True)
print("namespaces:", json.dumps({k: str(v) for k, v in sparql.namespaces.items()}, indent=2))

print("properties:", json.dumps({sparql.graph.qname(k): str(v)
      for k, v in sparql.properties.items()}, indent=2))

print("connections:", json.dumps({sparql.graph.qname(k): str(v)
      for k, v in sparql.connections.items()}, indent=2))

namespaces: {
  "t": "http://aperturedb.io/type/",
  "c": "http://aperturedb.io/connection/",
  "p": "http://aperturedb.io/property/",
  "o": "http://aperturedb.io/object/",
  "knn": "http://aperturedb.io/knn/",
  "GENRE": "http://aperturedb.io/object/GENRE/",
  "KEYWORD": "http://aperturedb.io/object/KEYWORD/",
  "MOVIE": "http://aperturedb.io/object/MOVIE/",
  "PRODUCTION_COMPANY": "http://aperturedb.io/object/PRODUCTION_COMPANY/",
  "PROFESSIONAL": "http://aperturedb.io/object/PROFESSIONAL/",
  "SPOKEN_LANGUAGE": "http://aperturedb.io/object/SPOKEN_LANGUAGE/"
}
properties: {
  "p:id": "{'PROFESSIONAL', 'MOVIE', 'GENRE', 'PRODUCTION_COMPANY', 'KEYWORD'}",
  "p:label": "{'PROFESSIONAL', 'MOVIE', 'GENRE', 'SPOKEN_LANGUAGE', 'PRODUCTION_COMPANY', 'KEYWORD'}",
  "p:name": "{'PROFESSIONAL', 'MOVIE', 'GENRE', 'SPOKEN_LANGUAGE', 'PRODUCTION_COMPANY', 'KEYWORD'}",
  "p:budget": "{'MOVIE'}",
  "p:movie_id": "{'MOVIE'}",
  "p:overview": "{'MOVIE'}",
  "p:popularity": "{'MOVIE'}",
  "p:tagline": "{'MOVIE'}",
  "p:title": "{'MOVIE'}",
  "p:vote_average": "{'MOVIE'}",
  "p:vote_count": "{'MOVIE'}",
  "p:gender": "{'PROFESSIONAL'}",
  "p:iso_639_1": "{'SPOKEN_LANGUAGE'}"
}
connections: {
  "c:CAST": "({'MOVIE'}, {'PROFESSIONAL'})",
  "c:CREW": "({'MOVIE'}, {'PROFESSIONAL'})",
  "c:HAS_GENRE": "({'MOVIE'}, {'GENRE'})",
  "c:HAS_KEYWORD": "({'MOVIE'}, {'KEYWORD'})",
  "c:HAS_PRODUCTION_COMPANY": "({'MOVIE'}, {'PRODUCTION_COMPANY'})",
  "c:HAS_SPOKEN_LANGUAGE": "({'MOVIE'}, {'SPOKEN_LANGUAGE'})"
}

### Find all the movies where Tom Hanks as been a part of

In [13]:

query = """
SELECT  ?title ?pop ?budget
WHERE {
  ?p p:name "Tom hanks" .
  ?m c:CAST ?p .
  ?m p:title ?title ;
    p:popularity ?pop ;
    p:budget ?budget .
}
"""

results = sparql.query(query)
df = sparql.to_dataframe(results)
display(df)

                                title         pop     budget
0   Extremely Loud & Incredibly Close   31.066874   40000000
1                        Philadelphia   44.301745   26000000
2                         Toy Story 3   59.995418  200000000
3                   The Polar Express   47.323228  165000000
4                 Saving Private Ryan   76.041867   70000000
5                           Apollo 13   68.140214   52000000
6                     You've Got Mail   28.540267   65000000
7                      The Green Mile  103.698022   60000000
8                    Saving Mr. Banks   31.957947   35000000
9                     The Ladykillers   23.666229          0
10       Who Killed the Electric Car?    5.323184    1000000
11                    Angels & Demons   67.447636  150000000
12                        Radio Flyer    3.503408   35000000
13                             Splash   21.735068    8000000
14                  The Da Vinci Code   45.313197  125000000
15                       Forrest Gump  138.133331   55000000
16                   Captain Phillips   52.786917   55000000
17                Catch Me If You Can   73.944049   52000000
18                          Toy Story   73.640445   30000000
19                        Cloud Atlas   73.872343  102000000
20                        Toy Story 2   73.575118   90000000
21                          Cast Away   57.739713   90000000
22                       Larry Crowne   20.355458   30000000
23                 That Thing You Do!   14.885388          0
24                  Road to Perdition   49.078546   80000000
25                                Big   20.716023   18000000
26                       The Terminal   57.753914   60000000
27               Charlie Wilson's War   18.700310   75000000
28                 The Simpsons Movie   46.875375   75000000
29                               Cars   82.643036  120000000
30              A League of Their Own   21.661028   40000000
31                    Bridge of Spies   48.445978   40000000

### Find 2 cast people. Find the movies they have been part of.

In [14]:
query = """
SELECT  ?title ?pop ?budget
WHERE {
  ?m c:CAST [p:name "Tom hanks"] , [p:name "Meg ryan"] ;
    p:title ?title ;
    p:popularity ?pop ;
    p:budget ?budget .
}
"""

results = sparql.query(query)
df = sparql.to_dataframe(results)
display(df)
# print(json.dumps(sparql.input_query, indent=2))

             title        pop    budget
0  You've Got Mail  28.540267  65000000